name: grain
description: Wrap your widgets in an aesthetic, old film grain.
version: 0.0.1
repository: https://github.com/breitburg/grain


environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/grain.png
  